//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebo.Mobi.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebo.Mobi.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить новый профиль..
        /// </summary>
        internal static string bAddUser {
            get {
                return ResourceManager.GetString("bAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bot {
            get {
                object obj = ResourceManager.GetObject("bot", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Закрыть текущий профиль..
        /// </summary>
        internal static string bRemoveUser {
            get {
                return ResourceManager.GetString("bRemoveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить настройки..
        /// </summary>
        internal static string bSave {
            get {
                return ResourceManager.GetString("bSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск бота для текущего профиля..
        /// </summary>
        internal static string bStart {
            get {
                return ResourceManager.GetString("bStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запуск бота для всех профилей..
        /// </summary>
        internal static string bStartAll {
            get {
                return ResourceManager.GetString("bStartAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка бота для текущего профиля..
        /// </summary>
        internal static string bStop {
            get {
                return ResourceManager.GetString("bStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Остановка бота для всех профилей..
        /// </summary>
        internal static string bStopAll {
            get {
                return ResourceManager.GetString("bStopAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать программу вместе с Windows и по возможности запускать бота для всех профилей..
        /// </summary>
        internal static string cbAutorun {
            get {
                return ResourceManager.GetString("cbAutorun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не собирать награды (полезно по выходным)..
        /// </summary>
        internal static string cbDoNotGetRevard {
            get {
                return ResourceManager.GetString("cbDoNotGetRevard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выкладывать товар. Полезно перед походом к инвесторам..
        /// </summary>
        internal static string cbDoNotPut {
            get {
                return ResourceManager.GetString("cbDoNotPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если активно, пароль для текущего пользователя сохранен не будет..
        /// </summary>
        internal static string cbDoNotSaveThePass {
            get {
                return ResourceManager.GetString("cbDoNotSaveThePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не обновлять страницу статистики (экономит время и трафик).
        /// </summary>
        internal static string cbDoNotShowStatistic {
            get {
                return ResourceManager.GetString("cbDoNotShowStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выселять жильцов ниже заданного уровня..
        /// </summary>
        internal static string cbFire {
            get {
                return ResourceManager.GetString("cbFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выселять жильцов со знаком (-)..
        /// </summary>
        internal static string cbFire9 {
            get {
                return ResourceManager.GetString("cbFire9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать программу свернутой в трей. Доступно только вместе с автозапуском..
        /// </summary>
        internal static string cbHide {
            get {
                return ResourceManager.GetString("cbHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По возможности приглашать в город других игроков..
        /// </summary>
        internal static string cbInvite {
            get {
                return ResourceManager.GetString("cbInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашать игроков с уровнем, не меньше заданного..
        /// </summary>
        internal static string cbInviteFrom {
            get {
                return ResourceManager.GetString("cbInviteFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приглашать игроков с уровнем не больше заданного..
        /// </summary>
        internal static string cbInviteTo {
            get {
                return ResourceManager.GetString("cbInviteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fon {
            get {
                object obj = ResourceManager.GetObject("fon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hd_nebo {
            get {
                object obj = ResourceManager.GetObject("hd_nebo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lift {
            get {
                object obj = ResourceManager.GetObject("lift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap man_minus {
            get {
                object obj = ResourceManager.GetObject("man_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mn_gold {
            get {
                object obj = ResourceManager.GetObject("mn_gold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mn_iron {
            get {
                object obj = ResourceManager.GetObject("mn_iron", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_f {
            get {
                object obj = ResourceManager.GetObject("player_f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_f_30 {
            get {
                object obj = ResourceManager.GetObject("player_f_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_f_40 {
            get {
                object obj = ResourceManager.GetObject("player_f_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_f_50 {
            get {
                object obj = ResourceManager.GetObject("player_f_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_f_60 {
            get {
                object obj = ResourceManager.GetObject("player_f_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_f_70 {
            get {
                object obj = ResourceManager.GetObject("player_f_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_m {
            get {
                object obj = ResourceManager.GetObject("player_m", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_m_30 {
            get {
                object obj = ResourceManager.GetObject("player_m_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_m_40 {
            get {
                object obj = ResourceManager.GetObject("player_m_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_m_50 {
            get {
                object obj = ResourceManager.GetObject("player_m_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_m_60 {
            get {
                object obj = ResourceManager.GetObject("player_m_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap player_m_70 {
            get {
                object obj = ResourceManager.GetObject("player_m_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap st_builded {
            get {
                object obj = ResourceManager.GetObject("st_builded", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap st_stocked {
            get {
                object obj = ResourceManager.GetObject("st_stocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//WAPFORUM//DTD XHTML Mobile 1.0//EN&quot; &quot;http://www.wapforum.org/DTD/xhtml-mobile10.dtd&quot;&gt;
        ///&lt;!--suppress ALL --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;http://nebo.mobi/images/style.css?v=83&quot;/&gt;
        ///    &lt;title&gt;Старт&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//WAPFORUM//DTD XHTML Mobile 1.0//EN&quot; &quot;http://www.wapforum.org/DTD/xhtml-mobile10.dtd&quot;&gt;
        ///&lt;!--suppress ALL --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;http://nebo.mobi/images/style.css?v=83&quot;/&gt;
        ///    &lt;title&gt;Старт&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body clas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string start_off {
            get {
                return ResourceManager.GetString("start_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//WAPFORUM//DTD XHTML Mobile 1.0//EN&quot; &quot;http://www.wapforum.org/DTD/xhtml-mobile10.dtd&quot;&gt;
        ///&lt;!--suppress ALL --&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;/&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;/&gt;
        ///    &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;http://nebo.mobi/images/style.css?v=83&quot;/&gt;
        ///    &lt;title&gt;Профиль&lt;/title&gt;
        ///  &lt;/head&gt;
        ///  &lt;body cl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb_empty {
            get {
                object obj = ResourceManager.GetObject("tb_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb_lift {
            get {
                object obj = ResourceManager.GetObject("tb_lift", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb_sold {
            get {
                object obj = ResourceManager.GetObject("tb_sold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tb_stocked {
            get {
                object obj = ResourceManager.GetObject("tb_stocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уровень, жильцы ниже которого будут автоматически выселены. .
        /// </summary>
        internal static string tbFireLess {
            get {
                return ResourceManager.GetString("tbFireLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный уровень приглашаемого игрока..
        /// </summary>
        internal static string tbInviteFrom {
            get {
                return ResourceManager.GetString("tbInviteFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальный уровень приглашаемого игрока.
        /// </summary>
        internal static string tbInviteTo {
            get {
                return ResourceManager.GetString("tbInviteTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя профиля. Чувствительно к регистру!.
        /// </summary>
        internal static string tbLogin {
            get {
                return ResourceManager.GetString("tbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное время (в минутах), через которое бот будет повторять работу. .
        /// </summary>
        internal static string tbMaxTime {
            get {
                return ResourceManager.GetString("tbMaxTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное время (в минутах), через которое бот будет повторять работу..
        /// </summary>
        internal static string tbMinTime {
            get {
                return ResourceManager.GetString("tbMinTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль профиля. Хранится в шифрованном виде. Чувствителен к регистру!.
        /// </summary>
        internal static string tbPass {
            get {
                return ResourceManager.GetString("tbPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users {
            get {
                object obj = ResourceManager.GetObject("users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_minus {
            get {
                object obj = ResourceManager.GetObject("users_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_plus {
            get {
                object obj = ResourceManager.GetObject("users_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap waiting {
            get {
                object obj = ResourceManager.GetObject("waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
